# yaml configuration file for linker/loader of Co-RTOS

Cores: 2  # must agree with the processor used
ThreadsPerCore: 2  # must agree with the processor used

Programs: # name all your programs ajit_entry_bget.c or specify here.
  - Dir: ./00
    Core: 0
    Thread: 0
  - Dir: ./01
    Core: 0
    Thread: 1

TotalMemoryInKB: 102400