# yaml configuration file for linker/loader of Co-RTOS
# yaml 10 minutes tutorial:
#   https://www.youtube.com/watch?v=cdLNKUoMc6c

Hardware:
  Processor:
    # Required: Number of cores and threads per core.
    Cores: 1
    ThreadsPerCore: 1

  Memory:
    MaxAddrBitWidth: 36
    Flash:
      StartAddr: 0x0  # physical address
      # EndAddr: ...
      # SizeInBytes: ...
      # SizeInKiloBytes: ...
      SizeInMegaBytes: 16
      Permissions: RXC  # (Read,Write,eXecute,Cacheable)
    Ram:
      StartAddr:   0x4FFFFFFF  # physical address
      # EndAddr: ...
      # SizeInBytes: ...
      # SizeInKiloBytes: ...
      SizeInMegaBytes: 128
      Permissions: RWXC
    MemoryMappedIo:
      StartAddr:   0xFFFF0000  # physical address
      # EndAddr: ...
      # SizeInBytes: ...
      # SizeInKiloBytes: ...
      SizeInKiloBytes: 4
      Permissions: RW

Software:
  Build:
    # Optional: Specify the log level. Default is NONE.
    # ALL < TRACE < DEBUG < INFO < ERROR < CRITICAL < NONE
    LogLevel: DEBUG
    OptimizationLevel: 2 # i.e. O2 (Accepted values: 0, 1, 2)
    EnableSerial: Yes
    Debug: No
    FirstDebugPort: 8000

  # Required: Which functions execute on each ajit thread.
  ProgramThreads:
    - CortosInitCalls:
        - main
  # One can also specify an infinite loop on the function:
  #   CortosLoopCalls:
  #     - main
      StackSizeInBytes: 8192

